imports:
    - { resource: tables.yml }
services:
    dmzx.donation.controller:
        class: dmzx\donation\controller\donation
        arguments:
            - @config
            - @controller.helper
            - @template
            - @user
            - @dbal.conn
            - @request
            - %dmzx.donation.table.donation%
    dmzx.donation.admin.controller:
        class: dmzx\donation\controller\admin_controller
        arguments:
            - @config
            - @template
            - @log
            - @user
            - @dbal.conn
            - @request
            - %dmzx.donation.table.donation%
    dmzx.donation.listener:
        class: dmzx\donation\event\listener
        arguments:
            - @config
            - @controller.helper
            - @template
        tags:
            - { name: event.listener }
